- src/pages/index.mdx
- src/pages/tutorials/instana/bee-travels/index.mdx
> Fix pages so npm run can work

- src/pages/index.mdx
- src/pages/tutorials/mm/mm-install/index.mdx
> rolling back src/pages/index.mdx to get the site built

- src/pages/index.mdx
> fixed top level index.mdx

- src/pages/tutorials/instana/administer/index.mdx
- src/pages/tutorials/instana/agent/index.mdx
- src/pages/tutorials/instana/explore/index.mdx
- src/pages/tutorials/instana/ibm-middleware/index.mdx
- src/pages/tutorials/instana/robot-shop/index.mdx
- src/pages/tutorials/instana/server/index.mdx
Fixed a few minor bugs including numbering schemes.
> changed numbering

- src/pages/tutorials/mm/mm-mad/index.mdx
> Fixed some of the MAD labs

- src/pages/tutorials/aiops/connections/index.mdx
- src/pages/tutorials/aiops/fullyAutomatedRunbooks/index.mdx
- src/pages/tutorials/aiops/optionalGrouping/index.mdx
- src/pages/tutorials/aiops/semiAutomatedRunbooks/index.mdx
> httpd -> apache2

- src/pages/tutorials/aiops/optionalGrouping/index.mdx
- src/pages/tutorials/aiops/semiAutomatedRunbooks/index.mdx
- src/pages/tutorials/aiops/temporalGrouping/index.mdx
> Session feedback

- src/pages/tutorials/aiops/scopeBasedGrouping/index.mdx
Added additional verbose for executing the event creation scripts and its correct environment requirements.
> Additional verbose for executing the event creation scripts and its correct environment requirements.

- src/pages/tutorials/mm/mm-install/index.mdx
> fix db2 startup

- src/pages/tutorials/aiops/fullyAutomatedRunbooks/index.mdx
> fixed error

- src/pages/tutorials/aiops/fullyAutomatedRunbooks/index.mdx
- src/pages/tutorials/mm/mm-analyzing-results/index.mdx
- src/pages/tutorials/mm/mm-install/index.mdx
- src/pages/tutorials/mm/mm-mad/index.mdx
- src/pages/tutorials/mm/mm-mediating-csv/index.mdx
- src/pages/tutorials/mm/mm-mediating-rest/index.mdx
> fix numbering, stressing pitfalls

- src/pages/tutorials/aiops/fullyAutomatedRunbooks/index.mdx
> Fixed curl issue

- src/pages/tutorials/mm/aimgr-install/index.mdx
> change to 1-1

- src/pages/tutorials/mm/aimgr-install/index.mdx
- src/pages/tutorials/mm/mm-install/index.mdx
> minor changes

- src/pages/tutorials/aiops/configureTopology/index.mdx
> Removing reference to on-prem server

- src/pages/tutorials/instana/ibm-middleware/index.mdx
Signed-off-by: Amar Kalsi <amarkalsi@uk.ibm.com>
> make it clear qotd is on the manage-to cluster

- src/pages/tutorials/mm/mm-mad/index.mdx
- src/pages/tutorials/mm/mm-mediating-rest/index.mdx
> fix issue with spark, and issue with curl command in lab 7

- src/pages/tutorials/mm/mm-mad/index.mdx
> Minor fix to step in lab 7

- src/pages/tutorials/aiops/connections/index.mdx
Signed-off-by: BOON SUAN TAN <tanlbs@my.ibm.com>
> remove hardcode nodeport in Section 3.3 to avoid confusion

- src/pages/tutorials/mm/aimgr-install/index.mdx
- src/pages/tutorials/mm/mm-install/index.mdx
- src/pages/tutorials/mm/mm-mediating-csv/index.mdx
> Jason's pre-APAC updates

- src/pages/tutorials/aiops/installation/index.mdx
> Fix the index for 2-5 in evtmgr deployment

- src/pages/tutorials/mm/aimgr-install/index.mdx
> fix link to catalog source installation

- src/pages/tutorials/turbonomic/kubeturbo/index.mdx
- src/pages/tutorials/turbonomic/policy/index.mdx
Signed-off-by: BOON SUAN TAN <tanlbs@my.ibm.com>
> Fix export ROBOTSHOP_URL

- src/pages/tutorials/instana/ibm-middleware/index.mdx
Signed-off-by: deepblue2k <yongjie.guo@ibm.com>
> updated instana 5-2 http for qotd

- .github/workflows/deploy.yml
Signed-off-by: Ryan Hay <ryanhay@au.ibm.com>
> test GitHub Actions user

- .github/workflows/deploy.yml
Signed-off-by: Ryan Hay <ryanhay@au.ibm.com>
> test GitHub Actions user with PAT

- labs/instana/2-server-installation/index.mdx
fix instana feature flag settings code block.
> Xin update 1018

- labs/general/index.md
- src/pages/snippets/index.md
- snippets page
- global pull secret info
> techjam: pull secret info & snippets

- labs/_common/components/tech-zone-status.module.css
- labs/_common/components/tech-zone-status.tsx
- labs/cloud-pak-aiops/alert-lab/2-lab-environment/index.md
- labs/cloud-pak-aiops/install-lab/2-lab-environment/index.md
- labs/cloud-pak-aiops/topology-lab/2-lab-environment/index.md
- labs/instana/administer-instana/2-lab-environment/index.mdx
- labs/instana/applications-and-ibm-middleware/2-lab-environment/index.mdx
- labs/instana/explore-instana/2-lab-environment/index.mdx
- labs/instana/opentelemetry/2-lab-environment/index.mdx
- labs/instana/server-and-agent-install-lab/2-lab-environment/index.mdx
- labs/instana/synthetic-pop/2-lab-environment/index.mdx
- labs/jam-in-a-box/index.md
- labs/turbonomic/install-lab/2-lab-environment/index.mdx
- labs/turbonomic/policies-and-taking-actions-lab/2-lab-environment/index.mdx
- labs/turbonomic/ui-and-k8s-data-target-lab/2-lab-environment/index.mdx
- src/css/custom.css
- tsconfig.json
Signed-off-by: Ryan Hay ryanhay@au.ibm.com
- Add live status on Tech Zone data center usage on each 'Lab Environment' page under 'Requesting a Lab Environment'
- Increase visual warning about Instana keys not being optional during environment provisioning.
> dc status and optional key warnings

- labs/_common/components/tech-zone-status.module.css
- labs/_common/components/tech-zone-status.tsx
- labs/instana/administer-instana/2-lab-environment/index.mdx
- labs/instana/applications-and-ibm-middleware/2-lab-environment/index.mdx
- labs/instana/explore-instana/2-lab-environment/index.mdx
- labs/instana/opentelemetry/2-lab-environment/index.mdx
- labs/instana/server-and-agent-install-lab/2-lab-environment/index.mdx
- labs/instana/synthetic-pop/2-lab-environment/index.mdx
- labs/turbonomic/install-lab/2-lab-environment/index.mdx
- labs/turbonomic/policies-and-taking-actions-lab/2-lab-environment/index.mdx
- labs/turbonomic/ui-and-k8s-data-target-lab/2-lab-environment/index.mdx
Signed-off-by: Ryan Hay [ryanhay@au.ibm.com]
> license info & capacity legend

- labs/turbonomic/install-lab/3-installation/index.mdx
- labs/turbonomic/ui-and-k8s-data-target-lab/4-kubeturbo/index.mdx
Signed-off-by: Ryan Hay ryanhay@au.ibm.com
> Bump turbo version CRs

- labs/instana/introduction/index.md
Remove overview descriptions for Otel and Synthetics labs until they are completed.
> instana overview

- labs/practitioner-basics/4-monitoring/_category_.json
- labs/practitioner-basics/4-monitoring/configuring-self-monitoring.mdx
- labs/practitioner-basics/4-monitoring/example-dashboards/aiops-health-overview.json
- labs/practitioner-basics/4-monitoring/example-dashboards/kafka.json
- labs/practitioner-basics/4-monitoring/example-dashboards/lifecycle.json
This PR adds an additional page detailing some strategies for self-monitoring IBM CloudPak for AIOps.
> feat: add page documenting self-monitoring

- labs/cloud-pak-aiops/migration-from-netcool/2-lab-environment/index.mdx
- labs/cloud-pak-aiops/migration-from-netcool/_category_.json
Signed-off-by: Ryan Hay <ryanhay@au.ibm.com>
To revert changes:
Update file `labs/cloud-pak-aiops/migration-from-netcool/_category_.json` to:
```json
{
"label": "Migration from Netcool",
"position": 20,
}
```
> tj aiops lab docs

- labs/cloud-pak-aiops/install-lab/3-installation/index.mdx
- labs/cloud-pak-aiops/topology-lab/1-introduction/index.mdx
- labs/cloud-pak-aiops/topology-lab/4-topology-rules/index.mdx
> tj aiops labs updates

- labs/cloud-pak-aiops/alert-lab/2-lab-environment/index.md
- labs/cloud-pak-aiops/install-lab/2-lab-environment/index.md
- labs/cloud-pak-aiops/install-lab/3-installation/index.mdx
- labs/cloud-pak-aiops/migration-from-netcool/2-lab-environment/index.mdx
- labs/cloud-pak-aiops/migration-from-netcool/3-netcool-connector/index.mdx
- labs/cloud-pak-aiops/topology-lab/2-lab-environment/index.md
- package-lock.json
I updated the references to cp4waiops and changed them to cp4aiops.
I also tweaked the Netcool Connector mapping by adding a mapping for the suppressed attribute and updated the severity attribute so it was more robust (ie. could not have a null value).
> updated cp4waiops to cp4aiops

- labs/cloud-pak-aiops/migration-from-netcool/3-netcool-connector/index.mdx
- labs/cloud-pak-aiops/migration-from-netcool/5-housekeeping/index.mdx
- labs/cloud-pak-aiops/migration-from-netcool/7-migrate-custom-correlation/index.mdx
Made some updates to Netcool migration labs 3, 5, and 7.
> Updating my files

- labs/cloud-pak-aiops/migration-from-netcool/3-netcool-connector/index.mdx
Small fix to the mapping code section on 3. Set up the Netcool Connector
> small page fix to 3. Set up the Netcool Connector

- labs/practitioner-basics/3-storage/intro.mdx
- labs/practitioner-basics/4-monitoring/_category_.json
- labs/practitioner-basics/5-tips-and-tricks/_category_.json
- labs/practitioner-basics/5-tips-and-tricks/aiops-blogs.mdx
- labs/practitioner-basics/index.mdx
Michael asked me to compile and add my blog posts to our SWAT site. This is the addition of that.
> Added AIOps blog posts to Practitioner Basics

- labs/instana/applications-and-ibm-middleware/4-ibm-middleware/index.mdx
Fixing 2 broken links in **Monitoring IBM Middleware** lab section of Apps & Middleware.
> update broken links for Instana Apps & Middleware lab

- labs/instana/administer-instana/3-administer/index.mdx
- labs/instana/applications-and-ibm-middleware/3-robot-shop-installation/index.mdx
- labs/instana/applications-and-ibm-middleware/4-ibm-middleware/index.mdx
- labs/instana/server-and-agent-install-lab/3-server-installation/index.mdx
- labs/instana/server-and-agent-install-lab/4-agent-installation/index.mdx
Added some additional information to clarify.
> updated labs

- docusaurus.config.ts
- labs/instana/applications-and-ibm-middleware/3-robot-shop-installation/index.mdx
- labs/instana/applications-and-ibm-middleware/4-ibm-middleware/index.mdx
- labs/instana/opentelemetry/3-agent-installation/index.mdx
- labs/instana/opentelemetry/4-opentelemetry-instrumentation/index.mdx
- labs/instana/opentelemetry/7-otel-collector/index.mdx
- labs/instana/server-and-agent-install-lab/3-server-installation/index.mdx
- labs/instana/server-and-agent-install-lab/4-agent-installation/index.mdx
- labs/instana/synthetic-pop/3-synthetic/index.mdx
- package-lock.json
- package.json
- src/css/custom.css
codeblock hostnames, key dist diagram
> codeblock hostnames, key dist diagram
